trigger:
- main

pool:
  name: Default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'

- task: CopyFiles@2
  inputs:
    contents: 'target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'student-app-jar'
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
